# Generated by Django 3.2.4 on 2021-07-08 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelfs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='death',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='notice',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shelfs.serie'),
        ),
        migrations.AlterField(
            model_name='item',
            name='volume',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='in_loans',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='serie',
            name='world',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
