# Generated by Django 3.2.4 on 2021-07-08 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shelfs', '0002_auto_20210708_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='date_of_loan',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='loans',
            name='date_of_return',
            field=models.DateTimeField(null=True),
        ),
    ]
