# Generated by Django 3.2.4 on 2021-07-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelfs', '0007_alter_publisher_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
