# Generated by Django 3.2.4 on 2021-07-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelfs', '0008_alter_publisher_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='photos/items/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='photos/loans/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='photos/publishers/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='photos/series/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='photos/users/%Y/%m/%d/'),
        ),
    ]
