# Generated by Django 3.2.4 on 2021-07-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelfs', '0011_auto_20210702_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useritem',
            name='is_author',
        ),
        migrations.AddField(
            model_name='user',
            name='is_author',
            field=models.BooleanField(default=False),
        ),
    ]
