# Generated by Django 3.2.4 on 2021-07-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelfs', '0012_auto_20210703_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
