# Generated by Django 3.2.4 on 2021-07-03 10:51

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shelfs', '0013_auto_20210703_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('surname', models.CharField(max_length=30, null=True)),
                ('birthday', models.DateField(null=True)),
                ('death', models.DateField(null=True)),
                ('plc_of_brth', models.CharField(max_length=30, null=True)),
                ('plc_of_dth', models.CharField(max_length=30, null=True)),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('file', models.FileField(blank=True, null=True, upload_to='photos/users/%Y/%m/%d/')),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='death',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_author',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='user',
            name='plc_of_brth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='plc_of_dth',
        ),
        migrations.AddField(
            model_name='item',
            name='author',
            field=models.ManyToManyField(to='shelfs.Author'),
        ),
    ]
