# Generated by Django 3.2.4 on 2021-07-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelfs', '0014_auto_20210703_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_dead',
            field=models.BooleanField(default=False),
        ),
    ]
